<script lang="ts">
  import { SvelteFlow, Background, Controls, type Node, type Edge, type NodeTypes } from '@xyflow/svelte';
  import '@xyflow/svelte/dist/style.css'; // required, or nodes render unstyled
  import CosmographNode from './lib/CosmographNode.svelte';
  import DagNode from './lib/dag/DagNode.svelte';
  import { loadDag } from './lib/dag/loadDag';

  const nodeTypes: NodeTypes = { cosmograph: CosmographNode, dag: DagNode };

  // The pipeline DAG is generated by Nextflow (-with-dag, see nextflow.config)
  // and converted to wired nodes on load. The embedding views live below it as
  // resizable, titled Cosmograph nodes.
  const view = (id: string, x: number, y: number, v: string, title: string): Node => ({
    id, type: 'cosmograph', position: { x, y },
    width: 1100, height: 640,
    data: { view: v, title },
  });
  // pipeline order, left -> right: reduce/cluster grid, explore, sampled
  const clusteringNode = (y: number) =>
    view('grid', 0, y, 'clustering', 'Reduce · Clustering : hyperparameter grid view');
  const exploreNode = (y: number) =>
    view('umap', 1160, y, 'explore', 'UMAP2 : explore embedding space view');
  const sampledNode = (y: number) =>
    view('sampled', 2320, y, 'sampled', 'Sampled : representatives over embedding space');

  let nodes = $state<Node[]>([clusteringNode(360), exploreNode(360), sampledNode(360)]);
  let edges = $state<Edge[]>([]);

  $effect(() => {
    let alive = true;
    (async () => {
      const dag = await loadDag('./data', 'pipeline_dag.mmd', { dir: 'LR' });
      if (!alive || !dag) return;   // no run yet -> just the embedding views

      const maxY = Math.max(0, ...dag.nodes.map(n => n.position.y));
      const grid = clusteringNode(maxY + 220);
      const umap = exploreNode(maxY + 220);
      const sampled = sampledNode(maxY + 220);

      // Wire each view from the producing DAG stage (else a sink).
      const sink = dag.nodes.find(n => !dag.edges.some(e => e.source === n.id));
      const byLabel = (l: string) => dag.nodes.find(n => (n.data?.label as string) === l);
      const fromCluster = byLabel('Cluster') ?? byLabel('Ensemble') ?? sink;
      const fromEnsemble = byLabel('Ensemble') ?? sink;
      const fromReps = byLabel('Representatives') ?? fromEnsemble;

      const wire = (from: typeof sink, target: string): Edge[] =>
        from ? [{ id: `e_${from.id}_${target}`, source: from.id, target, animated: true }] : [];

      nodes = [...dag.nodes, grid, umap, sampled];
      edges = [...dag.edges, ...wire(fromCluster, 'grid'), ...wire(fromEnsemble, 'umap'), ...wire(fromReps, 'sampled')];
    })();
    return () => { alive = false; };
  });
</script>

<div class="workbench">
  <SvelteFlow bind:nodes bind:edges {nodeTypes} colorMode="dark" fitView>
    <Background />
    <Controls />
  </SvelteFlow>
</div>

<style>
  .workbench {
    height: 100vh;
    width: 100vw;
    overflow: hidden;
    background: #0b0e14;
  }
</style>
