<script lang="ts">
  import { SvelteFlow, Background, Controls, type Node, type Edge, type NodeTypes } from '@xyflow/svelte';
  import '@xyflow/svelte/dist/style.css'; // required, or nodes render unstyled
  import CosmographNode from './lib/CosmographNode.svelte';
  import DagNode from './lib/dag/DagNode.svelte';
  import { loadDag } from './lib/dag/loadDag';

  const nodeTypes: NodeTypes = { cosmograph: CosmographNode, dag: DagNode };

  // The pipeline DAG is generated by Nextflow (-with-dag, see nextflow.config)
  // and converted to wired nodes on load. The reconcile embedding view lives
  // below it as a resizable Cosmograph node.
  const reconcileNode = (y: number): Node => ({
    id: 'umap',
    type: 'cosmograph',
    position: { x: 0, y },
    width: 1100,
    height: 640,
    data: { view: 'reconcile' },   // After Ensemble · Reconcile embedding view
  });

  let nodes = $state<Node[]>([reconcileNode(360)]);
  let edges = $state<Edge[]>([]);

  $effect(() => {
    let alive = true;
    (async () => {
      const dag = await loadDag('./data', 'pipeline_dag.mmd', { dir: 'LR' });
      if (!alive || !dag) return;   // no run yet -> just the embedding view

      const maxY = Math.max(0, ...dag.nodes.map(n => n.position.y));
      const umap = reconcileNode(maxY + 220);

      // Wire the embedding view from the consensus producer (Ensemble), else a sink.
      const anchor =
        dag.nodes.find(n => (n.data?.label as string) === 'Ensemble') ??
        dag.nodes.find(n => !dag.edges.some(e => e.source === n.id));

      nodes = [...dag.nodes, umap];
      edges = anchor
        ? [...dag.edges, { id: `e_${anchor.id}_umap`, source: anchor.id, target: 'umap', animated: true }]
        : dag.edges;
    })();
    return () => { alive = false; };
  });
</script>

<div class="workbench">
  <SvelteFlow bind:nodes bind:edges {nodeTypes} colorMode="dark" fitView>
    <Background />
    <Controls />
  </SvelteFlow>
</div>

<style>
  .workbench {
    height: 100vh;
    width: 100vw;
    overflow: hidden;
    background: #0b0e14;
  }
</style>
